/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Thatchanon' at '10/7/16 1:35 PM' with Gradle 2.10
 *
 * @author Thatchanon, @date 10/7/16 1:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
